application: cadmis
version: 1
runtime: go
api_version: go1

handlers:

- url: /
  static_files : static/index.html
  upload: static

# apiへのリクエストはスクリプトで受ける
- url: /api/.*
  script: _go_app

# 各種ファイルへのリクエストハンドラ
- url: /
  static_dir : static

